### ISSUE TITLE
bungeecord启动报错

### ISSUE THREAD

**Issue by lupohan44** [lintx/Minecraft-Plugin-YinwuChat#1]
18:25:32 [警告] Exception encountered when loading plugin: YinwuChat
java.lang.NoClassDefFoundError: org/lintx/plugins/modules/configure/Configure 
    at org.lintx.plugins.yinwuchat.bungee.Config.load(Config.java:18) 
    at org.lintx.plugins.yinwuchat.bungee.YinwuChat.onEnable(YinwuChat.java:57) 
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:217) 
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:239) 
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:50) 
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) 
Caused by: java.lang.ClassNotFoundException: org.lintx.plugins.modules.configure.Configure 
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53) 
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27) 
    at java.lang.ClassLoader.loadClass(Unknown Source) 
    ... 6 more

**Comment by lintx** [comment]
需要前置插件
Let your Minecraft plugin load and save the configuration.让你的Minecraft插件一句代码加载、保存配置。 https://github.com/lintx/ConfigureCore-for-Minecraft-plugins

**Comment by lupohan44** [comment]
新报错
18:29:46 [警告] Exception encountered when loading plugin: YinwuChat
java.lang.NoSuchMethodError: net.md_5.bungee.config.Configuration: method <init>()V not found 
    at org.lintx.plugins.modules.configure.BungeeConfigure.load(BungeeConfigure.java:69) 
    at org.lintx.plugins.modules.configure.Configure.bungeeLoad(Configure.java:14) 
    at org.lintx.plugins.modules.configure.Configure.bungeeLoad(Configure.java:10) 
    at org.lintx.plugins.yinwuchat.bungee.Config.load(Config.java:18) 
    at org.lintx.plugins.yinwuchat.bungee.YinwuChat.onEnable(YinwuChat.java:57) 
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:217) 
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:239) 
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:50) 
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by lintx** [comment]
不需要理会，初始化配置文件时会发生

**Comment by lintx** [comment]
不是，版本不对的样子

**Comment by lupohan44** [comment]
怎么处理?

**Comment by lintx** [comment]
Configure的版本和Bungeecord的版本分别是多少

**Comment by lintx** [comment]
应该还是初始化配置时的警告，重启插件应该没有了

**Comment by lupohan44** [comment]
BC是快吧的专用BC configure的话releases只有一个版本 重启后依然有这个 而且配置文件也没生成

**Comment by lintx** [comment]
configure 明明有6个release，最新版本是1.2.1，重启还有就是版本问题

**Comment by lupohan44** [comment]
眼睛不好 就是1.2.1的 依然报错

**Comment by lintx** [comment]
那就升级bungeecord
https://ci.md-5.net/job/BungeeCord/

**Comment by lupohan44** [comment]
hmmmmm 问题是这个是快吧专用的BC← ←
